spring.datasource.url=jdbc:postgresql://localhost:5433/infofolga_db
spring.datasource.username=infofolga_user
spring.datasource.password=infofolga_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
api.security.token.secret=jZ5fL9sQv3xG8yW2rP6dC1bA4nU0kH7mF5eJ6vO8zT=