server.port=${PORT:8080}

spring.jpa.open-in-view=false

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

api.security.token.secret=${JWT_SECRET}

logging.level.org.springframework.security=DEBUG
logging.level.com.infoway.infofolga=INFO

spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.connection-timeout=20000

server.tomcat.threads.max=400
server.tomcat.accept-count=200